import {getWallet,openVault,normalizeAddress,assertWriteReady,verifyController,enforceRateLimit,canonical,fetchXProof,buildProof,tokenAmount,ok,fail} from "./shared.js";
const counts={buyback:5,withdraw:7,airdrop:7,execute:6};
export async function run(kind,args){if(args.length<counts[kind])throw new Error(`Invalid ${kind} arguments`);const w=getWallet();await assertWriteReady(w);const [requested,vaultArg]=args,{vault,token,contract}=await openVault(vaultArg,w);if(normalizeAddress(requested,"token").toLowerCase()!==token.toLowerCase())throw new Error(`Token mismatch; vault uses ${token}`);let tweetId,h,id,substring,send,extra={};
if(kind==="buyback"){[, ,tweetId,h,id]=args;await verifyController(contract,h,id,tweetId);if(await contract.lastGoodPrice()===0n)throw new Error("First buyback requires owner/guardian bootstrap via autoBuybackAuto(minOut > 0)");substring=canonical.buyback(token,vault);send=(p,s)=>contract.triggerBuybackByProof(0n,p,s)}
if(kind==="withdraw"){let amountInput,to;[, ,amountInput,to,tweetId,h,id]=args;to=normalizeAddress(to,"recipient");const amount=await tokenAmount(token,w,amountInput);if(amount<=0n)throw new Error("Amount must be positive");await verifyController(contract,h,id,tweetId);substring=canonical.withdraw(token,vault,amount.toString(),to);extra={amountRaw:amount.toString(),amountTokens:amountInput,to};send=(p,s)=>contract.withdrawVaultTaxtokenByProof(amount,to,p,s)}
if(kind==="airdrop"){let amountInput,max;[, ,amountInput,max,tweetId,h,id]=args;const amount=await tokenAmount(token,w,amountInput);max=BigInt(max);if(amount<=0n||max<=0n)throw new Error("Amount and maxClaimants must be positive");await verifyController(contract,h,id,tweetId);substring=canonical.airdrop(token,vault,amount.toString(),max.toString());extra={amountRaw:amount.toString(),amountTokens:amountInput,maxClaimants:max.toString()};send=(p,s)=>contract.setAirdropRoundByProof(amount,max,p,s)}
if(kind==="execute"){let proposal;[, ,proposal,tweetId,h,id]=args;proposal=BigInt(proposal);await verifyController(contract,h,id,tweetId);substring=canonical.execute(token,vault,proposal.toString());extra={proposalId:proposal.toString()};send=(p,s)=>contract.executeProposalByProof(proposal,p,s)}
enforceRateLimit(h);const d=await fetchXProof({tweetId,substring}),proof=buildProof(d.tweet_id,d.x_handle,d.x_id,d.substring),r=await(await send(proof,d.signature)).wait();ok({action:kind,token,vault,...extra,txHash:r.hash,blockNumber:r.blockNumber})}
export const main=kind=>run(kind,process.argv.slice(2)).catch(fail);
